const withSass = require("@zeit/next-sass");
const path = require("path");
// const webpack = require("webpack");

// * Just prefix url for assets generated by next (change on production or on port change or what ever you want)
const PUBLIC_URL = 'http://localhost:3000';

module.exports = withSass({
    assetPrefix: PUBLIC_URL,
    webpack(config, options) {

        // * Asking next webpack to allow for root folder imports by using "~/" syntax
        // * Used jsconfig to make VSCode able to handle such imports
        config.resolve.alias["~"] = path.resolve(__dirname);
        return config;
    }
});

